### ISSUE TITLE
(6) Attempt login to remote server

### ISSUE THREAD

**Issue by karikittie** [cs410agile-group3/FTPClient#27]
Parent: #1

The client should attempt a login using the remote server location and username provided at the command line. We should prompt for the password (making sure to obscure the type on terminal). Successful login doesn't need to print a message, at this point. Error should print something like "unable to login to remote server with error: {{ some error description }}"

**Comment by mkduer** [comment]
This ties into #57 for establishing a connection when running `dotnet run`, but has been set as a separate issue, so this one can be closed.
